Add Checking methods with tests
ardalis/Ardalis.Extensions pull request #41
Opened 2021-07-23 23:16 UTC by MoatazMohamedAllam

2021-07-23 23:29 UTC, josuave commented
I wonder if a better naming may be "Verification"

2021-07-23 23:40 UTC, MoatazMohamedAllam commented
yeah you are right it is a better name

2021-08-18 00:52 UTC, josuave commented
Is there a reason that these extension methods are in different namespaces?

2021-08-18 16:14 UTC, ardalis requested changes

2021-08-18 16:14 UTC, ardalis commented on src/Ardalis.Extensions/Checking/IsNull.cs
> +    public static partial class CheckingExtensionMethods
```suggestion
    public static partial class CheckingExtensions
```

2021-08-18 16:14 UTC, ardalis commented on src/Ardalis.Extensions/Checking/IsTrue.cs
> +    public static partial class CheckingExtensionMethods
```suggestion
    public static partial class CheckingExtensions
```

2021-08-18 16:14 UTC, ardalis commented on src/Ardalis.Extensions/Verification/IsNull.cs
> +    public static partial class CheckingExtensionMethods
```suggestion
    public static partial class CheckingExtensions
```

2021-08-18 16:14 UTC, ardalis commented on src/Ardalis.Extensions/Verification/IsTrue.cs
> +    public static partial class CheckingExtensionMethods
```suggestion
    public static partial class CheckingExtensions
```

2021-08-18 16:14 UTC, ardalis commented on src/Ardalis.Extensions/Verification/IsTrue.cs
> +namespace Ardalis.Extensions.Verification
What is the difference between `Verification` and `Checking` ?

2021-08-18 16:14 UTC, ardalis commented on tests/Ardalis.Extensions.UnitTests/Verification/IsTrueTests.cs
> +        public void ReturnsFalseGivenFalseCondition(bool condition)
Probably can be a `[Fact]` not a theory. Same for above.

2021-08-21 07:23 UTC, closed without merging